name: CI

on:
  push:
    branches: [ main ]
    tags: [ "**" ]
  pull_request:
    branches: [ main ]

env:
  PHP_VERSION: '8.2'
  COMPOSER_INSTALL_FLAGS: '--no-interaction --no-scripts --no-progress --optimize-autoloader --ansi --ignore-platform-reqs'

jobs:
  release:
    name: TER Upload
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - uses: tomasnorre/typo3-upload-ter@v2
        with:
          api-token: ${{ secrets.TYPO3_API_TOKEN }}
